<%@ Page Language="C#" AutoEventWireup="true" CodeFile="biometric-attendance.aspx.cs" Inherits="billing_software" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GST Ready Billing & Accounting Software At Lowest Price In Kottayam,Kerala. Best Billing Software In Kerala for all Traders. Suitable for Supermarket, Department Stores, Hyper Market, Ladies Store, Footwear Shop, Textile Billing POS, Eletcrical & Sanitary Shops, Wholesale Distributors, Hardware Shops, Computer Shops, Toy Shops Etc. Reliable & Trusted Service from Uniware Technologies Since 2011</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="GST  Billing Software in Kerala. Easy GST Return filing. Suitable for all traders like supermarket, textile shop, footwear shop, appliance store, electrical shop"/>
  <meta name="keywords" content="billing software dealer contact number in kottayam, kerala, how to get billing software in Kottayam, GST Billing Software for download in kottayam, Best Billing Software development companies in kottayam, Invoicing Software For GST return filing in kottayam, GST Reports making Software in kottayam, Billing Software In Cochin, Billing Software For Retailers and wholesalers, Low Cost Billing Software in kottayam, Free Billing Software download online, Free Accounting Software, Billing Software Download, Billing Software Free Download, GST Billing methods, Billing Software For Textiles, Billing Software For Grocery Shops, Billing Software For Supermarkets, Billing Software For Hypermarkets, Billing Software For Footwear Shops, Billing Software For Gift Shops, Billing Software For Hardware Shops, Billing Software For Electrical Shops, Where We Get Billing Software, How To Download Billing Software, Billing Software For Jewellery, Billing Software For Mobile Shops, online billing software for GST return filing, GST Return Filing Software, Billing Software With GST Return Filing, Accounting & Billing Software, Billing Software Like Tally For Free Use, Billing Software For Free Use At Kottayam, Changanachery, Billing Software Dealer In Kottayam, Billing Software Dealers In Kerala, Billing Software In Thiruvalla, Billing Software In Idukki, Billing Software supplier, Billing Software Installation"/>

  <meta name="author" content="Uniware Technologies"/>


  <meta property="og:type" content="product">
<meta property="og:title" content="">
<meta property="og:url" content="https://www.facebook.com/uniwaretech">
<meta property="og:image" content="https://external.fccj2-1.fna.fbcdn.net/safe_image.php?d=AQBPt6rJOfJ-jLIf&w=476&h=249&url=https%3A%2F%2Flh3.googleusercontent.com%2FxHp5euwL2d3FsBvBE33eyqzteHd0I4vxvl1Vk-_K9SYbSM_CZ_SMyRnC-QWb42ROfiCzleW8&cfs=1&upscale=1&fallback=news_d_placeholder_publisher&_nc_hash=AQCmmZykHaEGe6Ar">
<meta property="product:price:amount" content="8999">
<meta property="product:price:currency" content="INR">



  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

  <script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "GST Billing Software",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue" : "4.8",
    "ratingCount": "18",
    "reviewCount": "21"
  }
}
</script>





<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Uniware Technologies",
  "image" : "http://www.uniwareweb.com/img/logo.png",
  "telephone" : "+91 9656 73 7009",
  "email" : "uniwaretechnologies@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Near Railway Station",
    "addressLocality" : "Kottayam",
    "addressRegion" : "Kerala",
    "addressCountry" : "India",
    "postalCode" : "686 001"
  },
  "url" : "http://www.uniwareweb.com/"
}
</script>

   <link href="img/Icon.ico" rel="icon">
  <link href="img/Icon.ico" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/animate/animate.min.css" rel="stylesheet">
  <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <link href="css/style.css" rel="stylesheet">

</head>

<body>

  <header id="header">
    <div class="container-fluid">
  
      <div id="logo" class="pull-left">
         <a href="#intro"><img src="img/logo.png" alt="UNIWARE TECHNOLOGIES" title="" /></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="home.aspx">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Products</a></li>
          <li><a href="#portfolio">Services</a></li>
          <li class="menu-has-children"><a href="">Store</a>
            <ul>
              <li><a href="#">Barcode Printers</a></li>
              <li><a href="#">Barcode Scanners</a></li>
              <li><a href="#">Barcode Labels</a></li>
              <li><a href="#">Thermal Printer</a></li>
              <li><a href="#">Thermal Paper Rolls</a></li>
              <li><a href="#">Biometric Punching Machine</a></li>
              <li><a href="#">Face Detection Machine</a></li>
              <li><a href="#">Biomatric Access Control</a></li>
              <li><a href="#">RFID Tags & Strips</a></li>
              <li><a href="#">Students & Employees ID</a></li>
              <li><a href="#">Billing Machine</a></li>
              <li><a href="#">Boom Barrier</a></li>
              <li><a href="#">ID Card Printer</a></li>
            </ul>
          </li>
        <li><a href="#team">Career</a></li>
        <li><a href="https://uniwareweb.blogspot.com/" target="_blank">Blog</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <main id="main">

  
  
          

          <div style="position:relative;text-align:center;color:White; width:100%;">

                <img class="img img-fluid" src="img/Biometric-Punching-System-Banner.jpg" style="width:100%; margin-top:69px;" alt="Billing Software" />
                <div style="position:absolute; top:42%; left:15px;  ">
                    <h3 style="color:#d4d1ce; font-weight:500;">BIOMETRIC PUNCHING & ATTENDANCE SYSTEM </h3>

               </div>
          </div>

   <section id="contact" class="section-bg wow fadeInUp" style="padding-top:15px; padding-bottom:15px; background-color:#3F51B5;">
      <div class="container">

        <div class="section-header">
          <h3 style="margin-bottom:0px; color:White;">DROP YOUR CONTACT FOR FREE DEMO</h3>
          <p style="margin-bottom:0px; padding-bottom:12px; color:White;">Just leave your contact here...our expert will contact you very soon..!!</p>
        </div>

        <form id="Form1" runat="server">
        <div class="form">
          <div id="Div2"></div>
          <form action="" method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-5">
                <%--<input type="text" name="name" class="form-control" id="Text1" placeholder="Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />--%>
                <asp:TextBox class="form-control" placeholder="Enter Your Name" ID="TxtName" runat="server"></asp:TextBox>
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-5">
                
                <%--<input type="tel" class="form-control" name="email" id="email1" placeholder="Mobile Number" data-rule="email" data-msg="Please enter a valid email" />--%>
                <asp:TextBox class="form-control" placeholder="Enter Mobile Number" ID="TxtMobile" runat="server"></asp:TextBox>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server"  style="color:Red;" 
                ControlToValidate="TxtMobile" ErrorMessage="Enter a valid mobile number.."  
                ValidationExpression="[0-9]{10}"></asp:RegularExpressionValidator>
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-2">
              <div class="text-center">
                <%--<button type="submit">Submit Enquiry</button>--%>
                
                    <asp:Button ID="CmdSubmit" runat="server" Text="Submit Enquiry" 
                      onclick="CmdSubmit_Click"></asp:Button>
               
              </div>
 </form>

              </div>
         </form>
        </div>          
        </div>
      </div>
    </section>


    <section id="about" style="padding-top:40px;">
      <div class="container">

      <div class="row">
      <div class="col-sm-1"></div>
       <div class="col-sm-10">
        <header class="section-header">
          <h3>BILLING SOFTWARE WITH GST REPORTS</h3>
          <p style="font-size:15px; text-align:justify; margin-bottom:5px;"> e-Mark Classic, a powerful and fully featured billing and accounting software from Uniware Technologies. The software package includes all major features like item management, category management, purchase and stock management, GST billing, sales & purchase return, debtors & creditors management, Debit note/Credit note management, Sales Reports & Registers, Barcoding, Stock Verification, Profit & Sales Trend analysis, GST Retrun, GST Reports, HSN Summary reports etc.  </p>
        </header>
        </div> 
        <div class="col-sm-1"></div>
      </div>

      </div>
    </section>



        <section id="about">
      <div class="container">

<!--        <header class="section-header">
            <h3>MAJOR SOFTWARE PRODUCTS</h3>
        </header>-->
        <div class="row about-cols" style="margin-bottom:50px;">

          <div class="col-md-3 wow fadeInUp">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/supermarket.jpg" alt="Billing Software For Supermarkets" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">SUPERMARKET BILLING SOFTWARE</h2>
              <p>
                    GST Enabled billing & accounting software for supermarkets, hypermarkets & departmental stores. Barcode enabled billing terminal for ease of use.
              </p>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/textile.jpg" alt="Billing Software For Textile Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR TEXTILE SHOPS</h2>
              <p>
              Best billing software for Textile shops with integrated barcode printing system enables easy billing. The module integrated with accounting package.
              </p>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/footwear.jpg" alt="Billing Software For Bags & Footwear Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR FOOTWEAR SHOPS</h2>
              <p>
              GST Billing made easy for all retail and wholesale shops with e-Mark inventory management system. Custom invoice format for unique billing experience.
              </p>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/distributors.jpg" alt="Billing Software for Distributors & Dealers ( B2B )" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR DISTRIBUTORS</h2>
              <p>
                Advanced billing and accounting software for wholesale dealers and distributors with accurate reports. Barcode and RFID enabled for quick B2B billing.
              </p>
            </div>
          </div>

        </div>

         <div class="row about-cols" style="margin-bottom:50px;">
            
            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/furniture-shop.jpg" alt="Billing Software For Furniture Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR FURNITURE SHOPS</h2>
              <p>
                   GST Enabled Billing & Stock Management Software for furniture shops in Kerala. Manage your inventory and make GST return filing easy.
              </p>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/electrical.jpg" alt="Billing Software For Textile Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR ELECTRICAL SHOPS</h2>
              <p>
              GST Ready Billing & Accounting Software for small & large electrical shops. Very easy to use invoicing and stock management.
              </p>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/applicance.jpg" alt="Billing Software For Bags & Footwear Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR HOME APPLIANCE SHOP</h2>
              <p>
              Inventory And Billing management software, featured with GST, Cess & Accounting module. GST Return made easy with e-Mark.
              </p>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/emark/mobile-shop.jpg" alt="Billing Software For Mobile Shops" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;">BILLING SOFTWARE FOR MOBILE SHOPS</h2>
              <p>
                   Manage your Mobile Phone shop with <span style="color:Green;"><a href="http://www.emark.uniwareweb.com" target="_blank">e-Mark</a></span>, the fully featured billing & accounting software including Mobile Phone service module.
              </p>
            </div>
          </div>

         </div>


      </div>
    </section>                      




    <section id="call-to-action" class="wow fadeIn">
      <div class="container text-center">
        <h3>FOR FREE DEMO <br /> &<br /> QUICK INSTALLATION<br />CALL </h3>
        <h1 style="color:white; font-weight:bolder">+91 9656 73 7009</h1>
        <p> OR Tap the Call Button Below</p>
        <a class="cta-btn" href="tel:+91 9656737009" title="Click To Call Our Expert" data-rel="external">Call</a>
      </div>
    </section>

    <section id="services" style="padding-top:0px;">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3 style="margin-bottom:50px; margin-top:50px;">Key Features</h3>
        </header>

        <div class="row">

          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Easy To Use</a></h4>
            <p class="description">Easy to use billing software with GST. Custom invoice format for any business.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Customizable</a></h4>
            <p class="description">The software can be customised according to your requirement at any time.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Multiple Company</a></h4>
            <p class="description">The software comes with multiple company creation facility for large business.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">GST Return Resourses</a></h4>
            <p class="description">All reports and structured data required for GST return filing can be obtained.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Custom Reports</a></h4>
            <p class="description">Easily customizable reporting engine provides efficient and accurate reports.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Profit Analysis</a></h4>
            <p class="description">Strong analytical tools integrated with the software for profit analysis.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Auto Update</a></h4>
            <p class="description">Free software updates and major version upgradations in single click.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Life Time Licence</a></h4>
            <p class="description">Software licence issued for lifetime usage without any renewal charges</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Accounting Package</a></h4>
            <p class="description">Accounting module integrated with automatic posting and financial reports.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Barcode Integration</a></h4>
            <p class="description">In-built barcode labelling solution provided for supermarkets, textile shops etc.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Privilage Membership</a></h4>
            <p class="description">Membership management with privilage points incorporated for retail outlets.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">SMS Integration</a></h4>
            <p class="description">SMS notifications and promotional announcements through the system.</p>
          </div>
        </div>

      </div>
    </section>



<!--    <section id="portfolio"  class="section-bg" >
      <div class="container">

        <div class="row portfolio-container">

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emark.jpg" class="img-fluid" alt="e-Mark Classic Sales And Billing Software">
                <a href="img/portfolio/emark.jpg" data-lightbox="portfolio" data-title="App 1" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark Classic</a></h4>
                <h6>GST Enabled Billing & Accounting Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/escholar.jpg" class="img-fluid" alt="e-Scholar College Automation Software Package In Kerala">
                <a href="img/portfolio/escholar.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Scholar WEB</a></h4>
                <h6>A Complete College Automation Software Package</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcare.jpg" class="img-fluid" alt="SmartCARE HMS Hospital Management Software In Kerala">
                <a href="img/portfolio/smartcare.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">SmartCARE HMS</a></h4>
                <h6>Fully Featured Hospital Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emarkweb.jpg" class="img-fluid" alt="e-Mark Online Software For Billing & Accounting With GST">
                <a href="img/portfolio/emarkweb.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark WEB</a></h4>
                <h6>GST Ready Online Billing & Accounting Software including mobile app</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcrm.jpg" class="img-fluid" alt="Customer Relationship Management Software">
                <a href="img/portfolio/smartcrm.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CRM</a></h4>
                <h6>Well Organized Customer Relationship Management Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/whitestore.jpg" class="img-fluid" alt="e-Commerce Shopping Cart">
                <a href="img/portfolio/whitestore.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">White Store</a></h4>
                <h6>Complete e-Commerce Shopping Cart and Online Store Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/timestamp.jpg" class="img-fluid" alt="Biometric Attendance System using Finger Print, Palm And Face Reader">
                <a href="img/portfolio/timestamp.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">TimeStamp Pro</a></h4>
                <h6>Biometric Punching system for Time & Attendance Management</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/gdesk.jpg" class="img-fluid" alt="g-Desk Gymnesium Software For Membership Management, Progress Analysis And Fee Collection">
                <a href="img/portfolio/gdesk.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">G-Desk</a></h4>
                <h6>Customizable Gymnesium & Health club management system</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcms.jpg" class="img-fluid" alt="Content Management System For Dynamic Website">
                <a href="img/portfolio/smartcms.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CMS</a></h4>
                <h6>Free To Use Content Management System for business websites</h6>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
-->

  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Products</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Services</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Store</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="website.aspx">Web Designing</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Partner Program</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Safa Trade Centre<br>
              Railway Station Road<br>
              Kottayam, Kerala - 686 001 <br>
              <strong>Mobile:</strong> +91 9656 73 7009<br>
              <strong>Phone :</strong> 0481 256 1024<br>
              <strong>Email:</strong>uniwaretechnologies@gmail.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-6 col-md-6 footer-newsletter">
            <h4>Reach Us</h4>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3934.0713279352135!2d76.55078331417474!3d9.589120282606197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b062c7ef5a91a2b%3A0xfbe80bcc5a863194!2sUNIWARE+TECHNOLOGIES!5e0!3m2!1sen!2sin!4v1527671196207" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><a href="http://uniwareweb.com">UNIWARE TECHNOLOGIES</a></strong>. All Rights Reserved
      </div>

    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/jquery/jquery-migrate.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/superfish/hoverIntent.js"></script>
  <script src="lib/superfish/superfish.min.js"></script>
  <script src="lib/wow/wow.min.js"></script>
  <script src="lib/waypoints/waypoints.min.js"></script>
  <script src="lib/counterup/counterup.min.js"></script>
  <script src="lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="lib/isotope/isotope.pkgd.min.js"></script>
  <script src="lib/lightbox/js/lightbox.min.js"></script>
  <script src="lib/touchSwipe/jquery.touchSwipe.min.js"></script>

  <script src="contactform/contactform.js"></script>

  <script src="js/main.js"></script>


  
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5e3d2d5a298c395d1ce6afc3/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->


</body>


</html>

