<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Home" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Uniware Technologies | Software & Website Development Company in Kerala. Custom Software Development, Business Websites, IT Company In Kottayam, Software Company in Kottayam, Web designing Company in Kottayam, Software Training In Kottayam, IT Company In Kerala, Kottayam. Software For All Business, Business Software, Business Website, SEO company in kottayam, Billing Software In Kottayam, Billig Software With GST, GST Billing Software, POS Machine, Barcode Labels, Thermal Paper in Kottayam, Barcode Labels In Kottayam</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="Custom Software Development And IT Enabled Service Providing Company In Kottayam, Kerala. Quality Products At Reasonable Price With Professional Customer Support"/>
  <meta name="keywords" content="IT Company In Kottayam, IT companies in kottayam, Software Company in kottayam, Software Training Institute in Kottayam, Web Designing Companies In Kottayam, IT Companies Near Me, Computer Software developers in kottayam, Mobile Application Development in kottayam, Biometric Attendance system for offices in kottayam, Punching System machine and software, College Automation Software, Hospital Management System in kottayam, ERP Software, College Automation Software in Kottayam, College software, Software development companies in kottayam for College software, Students Information System Software developers in kottayam, Students Management Software, Fee Collection Software for schools and colleges, Online College Administration Software, Online Examination Software For Colleges, Attendance Software For Colleges and schools"/>
  <meta name="author" content="Uniware Technologies"/>


  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Uniware Technologies",
  "image" : "http://www.uniwareweb.com/img/logo.png",
  "telephone" : "+91 9656 73 7009",
  "email" : "uniwaretechnologies@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Kalathipady, KK Road",
    "addressLocality" : "Kottayam",
    "addressRegion" : "Kerala",
    "addressCountry" : "India",
    "postalCode" : "686 010"
  },
  "url" : "http://www.uniwareweb.com/"
}
</script>


  <!-- Google Tag Manager -->
        <script>            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({ 'gtm.start':
            new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-KPM8L5C');
        </script>

   <link href="img/Icon.ico" rel="icon">
  <link href="img/Icon.ico" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/animate/animate.min.css" rel="stylesheet">
  <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <link href="css/style.css" rel="stylesheet">

</head>

<body>

  <header id="header">
    <div class="container-fluid">
  
      <div id="logo" class="pull-left">
         <a href="#intro"><img src="img/logo.png" alt="UNIWARE TECHNOLOGIES" title="" /></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="home.aspx">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Products</a></li>
          <li><a href="#portfolio">Services</a></li>
          <li class="menu-has-children"><a href="Store.aspx">Store</a>
            <ul>
              <li><a href="Store.aspx#BarcodePrinter">Barcode Printers</a></li>
              <li><a href="Store.aspx#BarcodeScanner">Barcode Scanners</a></li>
              <li><a href="Store.aspx#BarcodeLabel">Barcode Labels</a></li>
              <li><a href="Store.aspx#ThermalPrinter">Thermal Printer</a></li>
              <li><a href="Store.aspx#ThermalPaperRoll">Thermal Paper Rolls</a></li>
              <li><a href="Store.aspx#BiometricPunchingMachine">Biometric Punching Machine</a></li>
              <li><a href="Face-Detection-Machine.aspx">Face Detection Machine</a></li>
              <li><a href="Store.aspx#BiometricAccessControl">Biomatric Access Control</a></li>
              <li><a href="Store.aspx#RFIDCard">RFID Card</a></li>
              <%--<li><a href="">Students & Employees ID</a></li>--%> 
              <li><a href="Store.aspx#BillingMachine">Billing Machine</a></li>
              <li><a href="Store.aspx#BoomBarriar">Boom Barrier</a></li>
              <li><a href="Store.aspx#IDCardPrinter">ID Card Printer</a></li>
            </ul>
          </li>
           <li><a href="Clients.aspx">Client</a></li>
        <li><a href="#team">Career</a></li>
        <li><a href="https://uniwareweb.blogspot.com/" target="_blank">Blog</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <div class="carousel-item active">
            <div class="carousel-background"><img src="img/intro-carousel/1.jpg" alt="Software Development"/></div>
            <div class="carousel-container">
              <div class="carousel-content">
              <h2>Custom Software Development</h2>
                <p>A Large Number Of Passionate And Enthusiastic Professionals Leading The Information Technology To Deliver High-End Software Solutions To Different Industries. We Are Passionate, We Make Solutions..!!</p>
                <a href="#featured-services" class="btn-get-started scrollto">Explore</a>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/2.jpg" alt="Web Designing In Kottayam"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Web Designing And Development</h2>
                <p>At Uniware Technologies, We Guarantee To Design & Develop Stunning Business Website For You. We Have Our In-House Designing Experts To Deliver Your Dream Web Site. We Are Passionate, We Design Your Dreams..!!</p>
                <a href="#featured-services" class="btn-get-started scrollto">Explore</a>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/3.jpg" alt="Digital Security & Punching System"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Digital Security Solutions</h2>
                <p>At Our Research And Development Department, We Have Set Up An Unbeatable Security Solution To Safe Guard Your Valuable Assets, With The Help Of All Most Modern Biometric, RFID, Access Control & CCTV Equipments.</p>
                <a href="#featured-services" class="btn-get-started scrollto">Explore</a>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/4.jpg" alt="Online Marketing & Website Promotion"></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Digital Marketing & Branding</h2>
                <p>Make Your Products & Services Reach Potential Customers And Convert The Leads To Valuable Business By Seting-Up A Top Level Position In Internet, Search Engine And Social Media Marketing.</p>
                <a href="#featured-services" class="btn-get-started scrollto">Explore</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </section>
  <main id="main">

    <section id="about">
      <div class="container">

      <div class="row">
      <div class="col-sm-1"></div>
       <div class="col-sm-10">
        <header class="section-header">
          <h3>About Us</h3>
          <p style="font-size:15px; text-align:justify; margin-bottom:5px;">At Uniware Technologies, we are focusing on delivering latest technology driven IT solutions such as ERP solutions, scalable business websites, mobile applications etc, to our customers with state of the art features. We have our fully satisfied customers across the country, having faith on the quality of our products and services, driving the growth of our company. We are always dedicated to keep customer satisfaction by giving newer features and updates all the time. </p>
          <p style="font-size:15px; text-align:justify; "> We have a very large team of experts in strategic consultation, designing, development & programming with lot of innovative ideas which benefited to our customers as well as the company. Uniware Technologies marked a top level position in the industry in a short span of time by taking challenges and delivering cost effect products and services.</p>
        </header>
        </div> 
        <div class="col-sm-1"></div>
      </div>

        <header class="section-header">
            <h3>MAJOR SOFTWARE PRODUCTS</h3>
        </header>
        <div class="row about-cols" style="margin-bottom:50px;">

          <div class="col-md-4 wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="img/CollegeAutomation.jpg" alt="Collge Automation Software In Kerala" class="img-fluid"/>
                <div class="icon"><i class="ion-university"></i></div>
              </div>
              <h2 class="title">COLLEGE AUTOMATION SOFTWARE</h2>
              <p>
                A fully featured package of Automation software for Colleges. The package includes all software modules required for the institution and succesfully implemented in many top graded colleges in Kerala.
              </p>
                <center><a href="CollageAutomation-Software.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col">
              <div class="img">
                <img src="img/BillingSoftware.jpg" alt="Billing Software In Kottayam, Kerala" class="img-fluid"/>
                <div class="icon"><i class="ion-ios-list-outline"></i></div>
              </div>
              <h2 class="title">BILLING SOFTWARE WITH ACCOUNTING</h2>
              <p>
                GST Enabled Billing Software with accounting, suitable for retail & wholesale shops, dealers, distributors, Mobile shops, Textile Outlets, Supermarkets etc. GST return filing made easy with simple reports. Get free demo & offers.
              </p>
                <center><a href="billing-software.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col">
              <div class="img">
                <img src="img/PunchingSoftware.jpg" alt="Biometric Attendance System & Punching Machine" class="img-fluid"/>
                <div class="icon"><i class="ion-ios-eye-outline"></i></div>
              </div>
              <h2 class="title">BIOMETRIC ATTENDANCE & SECURITY SYSTEMS</h2>
              <p>
                Time & Attendance Management (Punching) system using most modern biometric devices like fingerprint reader, palm reader, face reader, access control devices etc. Assosicated with Comprehensive and Feature rich Software.
              </p>
                <center><a href="biometric-attendance.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

        </div>

        <div class="row about-cols">

          <div class="col-md-4 wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="img/HospitalManagement.jpg" alt="Hospital Management Software In Kerala" class="img-fluid"/>
                <div class="icon"><i class="ion-ios-pulse"></i></div>
              </div>
              <h2 class="title">HOSPITAL MANAGEMENT SYSTEM</h2>
              <p>
                 Best software package for different types of Hospitals & other health care organisations. The package including Administration module, OP/IP management, Accounts, Pharmacy & Laboratory Management system etc.
              </p>
                <center><a href="HospitalManagementSoftware.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col">
              <div class="img">
                <img src="img/TravelDesk.jpg" alt="Taxi Operator Software For Collection And Customer Management" class="img-fluid"/>
                <div class="icon"><i class="ion-model-s"></i></div>
              </div>
              <h2 class="title">TRAVEL DESK AUTOMATION SOFTWARE</h2>
              <p>
                A mobile friendly online application for Taxi & Tour operators. The software featuring customer registration, taxi reservation, SMS notifications, collection management, vehicle & driver assignment, profit analysis etc.
              </p>
                <center><a href="TravelDeskSoftware.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col">
              <div class="img">
                <img src="img/Gymnesium.jpg" alt="Gymnesium Software For Membership Management & Collection" class="img-fluid"/>
                <div class="icon"><i class="ion-ios-person"></i></div>
              </div>
              <h2 class="title">GYMNESIUM MANAGEMENT SYSTEM</h2>
              <p>
                A highly optimized software for Health Club and Gymnesium Management. The software is useful to manage all membership related activities, subscription management, asset management, health progress analysis etc.
              </p>
                <center><a href="#featured-services" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

        </div>


        <div class="row about-cols">

          <div class="col-md-4 wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="img/OnlineShopping.jpg" alt="Hospital Management Software In Kerala" class="img-fluid"/>
                <div class="icon"><i class="ion-ios-cart"></i></div>
              </div>
              <h2 class="title">ONLINE SHOPPING CART</h2>
             <center> <p>
                 Best online shopping cart. The package including Customer login, Offer Smart Search Option, One Click to Add to Cart, Security etc.
              </p></center>
                <center><a href="Online-Shopping-Cart.aspx" class="btn-get-started scrollto">Know More</a></center>
            </div>
          </div>

        </div>


      </div>
    </section>

          <div style="margin-top:30px;">
    <center><h3>HANDS-ON EXPERIENCES</h3></center>
    </div>

    <section id="featured-services">

      <div class="container">
        <div class="row">

          <div class="col-lg-4 box">
            <i class="ion-university"></i>
            <h4 class="title"><a href="">Edcucation Sector</a></h4>
            <p class="description">Automation projects in educational institutions such as Colleges, Engineering Colleges, Schools, Technical Education institutions etc.</p>
          </div>

          <div class="col-lg-4 box box-bg">
            <i class="ion-ios-home-outline"></i>
            <h4 class="title"><a href="">Government Sector</a></h4>
            <p class="description">Biometric punching system in government offices, municipalities, licenced software for different government departments etc.</p>
          </div>

          <div class="col-lg-4 box">
            <i class="ion-ios-briefcase-outline"></i>
            <h4 class="title"><a href="">Travel & Tourism</a></h4>
            <p class="description">Business websites, web applications, seo, smo, online advertisement etc for different travel and tourism operators in India.</p>
          </div>

        </div>
      </div>
    <div class="container">
        <div class="row">

          <div class="col-lg-4 box box-bg">
            <i class="ion-ios-pulse"></i>
            <h4 class="title"><a href="">Health Care Industry</a></h4>
            <p class="description">Software automation implemented in different Hospitals, Nursing stations, Dispensories, Pharmacies, Laboratories etc.</p>
          </div>

          <div class="col-lg-4 box">
            <i class="ion-paper-airplane"></i>
            <h4 class="title"><a href="">Overseas Projects</a></h4>
            <p class="description">Overseas software projects for different organisations from major countries like United States, Canada, Australia, UAE etc.</p>
          </div>

          <div class="col-lg-4 box box-bg">
            <i class="ion-radio-waves"></i>
            <h4 class="title"><a href="">Biometric, RFID & GPS</a></h4>
            <p class="description">We have succesfully implemented Punching system for attendance, RFID chip integration in libraries, GPS navigation system for school bus etc</p>
          </div>

        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>IT & Software Services</h3>
          <p>In addition to our software projects, we deliver best IT related services in India. We have a strong support of our valuable customers, having faith on our products and support, empowering the growth of our company. Find out some of our featured services.</p>
        </header>

        <div class="row">

          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-analytics-outline"></i></div>
            <h4 class="title"><a href="">Web Designing</a></h4>
            <p class="description">Production & Maintenance of Portfolio & Business websites, designing of e-Brochures, e-Marketing meterials etc. <a href="website.aspx">Explore</a></p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-bookmarks-outline"></i></div>
            <h4 class="title"><a href="">Software Development</a></h4>
            <p class="description">Custom Software development for all industries, using latest technologies at very reasonable pricing. </p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-paper-outline"></i></div>
            <h4 class="title"><a href="">Digital Marketing</a></h4>
            <p class="description">We provide digital marketing of your products and services using most modern platforms available in the industry.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
            <h4 class="title"><a href="">e-Commerce</a></h4>
            <p class="description">All-In-One market place to sell your products and services. Monitor, Manage & Grow your online business easily.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
            <h4 class="title"><a href="">SEO</a></h4>
            <p class="description">Improve your website traffice to get more business and reach your customers at right time using our SEO service.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-people-outline"></i></div>
            <h4 class="title"><a href="">SEM</a></h4>
            <p class="description">We do internet marketing and promote your websites by increasing it's visibility in search results mainly using paid advertisements</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
            <h4 class="title"><a href="">Social Media Marketing</a></h4>
            <p class="description">We use the benefits of social media networks to promote your websites & market your products and services.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
            <h4 class="title"><a href="">Website Development</a></h4>
            <p class="description">Stylish websites using latest technologies to make it compatible for smart devices such as smart phones, tabs etc.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-people-outline"></i></div>
            <h4 class="title"><a href="">Security Systems</a></h4>
            <p class="description">Biometric, RFID, Access Control, CCTV & GPS system for Time & Attendance management as well as security implementation.</p>
          </div>


        </div>

      </div>
    </section>

    <section id="call-to-action" class="wow fadeIn">
      <div class="container text-center">
        <h3>CALL FOR AN EXPERT ADVISE</h3>
        <p>We have a dedicated team of experts researching and analysing about the future technology developments, and how that can be made beneficial for our customers. Please feel free to click on the <span style="font-style:italic">Call</span> button to get an expert advise on your requirements</p>
        <a class="cta-btn" href="tel:+91 9656737009" title="Click To Call Our Expert" data-rel="external">Call</a>
      </div>
    </section>

    <section id="portfolio"  class="section-bg" >
      <div class="container">

        <header class="section-header">
          <h3 class="section-title">Our Portfolio</h3>
        </header>

        <div class="row">
          <div class="col-lg-12">
            <ul id="portfolio-flters">
              <li data-filter="*" class="filter-active">All</li>
              <li data-filter=".filter-app">App</li>
              <li data-filter=".filter-web">Web</li>
            </ul>
          </div>
        </div>

        <div class="row portfolio-container">

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emark.jpg" class="img-fluid" alt="e-Mark Classic Sales And Billing Software"/>
                <a href="img/portfolio/emark.jpg" data-lightbox="portfolio" data-title="App 1" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark Classic</a></h4>
                <h6>GST Enabled Billing & Accounting Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/escholar.jpg" class="img-fluid" alt="e-Scholar College Automation Software Package In Kerala"/>
                <a href="img/portfolio/escholar.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Scholar WEB</a></h4>
                <h6>A Complete College Automation Software Package</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcare.jpg" class="img-fluid" alt="SmartCARE HMS Hospital Management Software In Kerala"/>
                <a href="img/portfolio/smartcare.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">SmartCARE HMS</a></h4>
                <h6>Fully Featured Hospital Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emarkweb.jpg" class="img-fluid" alt="e-Mark Online Software For Billing & Accounting With GST">
                <a href="img/portfolio/emarkweb.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark WEB</a></h4>
                <h6>GST Ready Online Billing & Accounting Software including mobile app</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcrm.jpg" class="img-fluid" alt="Customer Relationship Management Software">
                <a href="img/portfolio/smartcrm.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CRM</a></h4>
                <h6>Well Organized Customer Relationship Management Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/whitestore.jpg" class="img-fluid" alt="e-Commerce Shopping Cart"/>
                <a href="img/portfolio/whitestore.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">White Store</a></h4>
                <h6>Complete e-Commerce Shopping Cart and Online Store Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/timestamp.jpg" class="img-fluid" alt="Biometric Attendance System using Finger Print, Palm And Face Reader"/>
                <a href="img/portfolio/timestamp.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">TimeStamp Pro</a></h4>
                <h6>Biometric Punching system for Time & Attendance Management</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/gdesk.jpg" class="img-fluid" alt="g-Desk Gymnesium Software For Membership Management, Progress Analysis And Fee Collection"/>
                <a href="img/portfolio/gdesk.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">G-Desk</a></h4>
                <h6>Customizable Gymnesium & Health club management system</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcms.jpg" class="img-fluid" alt="Content Management System For Dynamic Website"/>
                <a href="img/portfolio/smartcms.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CMS</a></h4>
                <h6>Free To Use Content Management System for business websites</h6>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>

    <!--==========================
      Clients Section
    ============================-->
    <section id="clients" class="wow fadeInUp">
      <div class="container">

        <header class="section-header">
          <h3>MAJOR CLIENTS</h3>
        </header>

        <div class="owl-carousel clients-carousel" >
          <img style="margin-right:10px;width:200px;" src="img/clients/Assumption_College.png"  alt="Assumption College Changanacherry"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Alphonsa_college.png" alt="Alphonsa College, Pala"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/BPC_College.png" alt="BPC College, Piravom, Ernakulam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Brilliant.png" alt="Brilliant Studey Centre, Pala"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Baselius_College.png" alt="Baselius College, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/KG_College_Pampady.png" alt="KG College, Pampady, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/MGU_Nursing_College.png" alt="Nursing College, MG University, Manimalakkunnu"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/MGU_DPS.png" alt="Pharmacy College, MG University, Puthuppally, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/SD_College_Kanjirappally.png" alt="SD College, Kanjirappally, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/StMarys_College_Manarcadu.png" alt="St.Marys College, Manarcardu, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/SN_College_Kumarakom.png" alt="SN College, Kumarakom, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Sankara_College_Kalady.png" alt="Sree Sankara College, Kalady, Ernakulam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/VNS_College_Konni.png" alt="VNS College of Arts And Science, Konni, Pathanamthitta"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Bhavapriya.jpg" alt="BavaPriya School of Music and Dance"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Kochintaxi.png" alt="Cochin taxi Rental"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/LaggageToLagoon.png" alt="Laggae To Lagoon"/>
           <img style="margin-right:10px;width:200px;" src="img/clients/Muncipality.png" alt="Kottayam-Muncipality"/>

        </div>

      </div>
    </section><!-- #clients  

    <!--==========================
      Clients Section
    ============================-->


    <section id="contact" class="section-bg wow fadeInUp">
      <div class="container">

        <div class="section-header">
          <h3>Contact Us</h3>
          <p>We always welcome you to keep in touch with us. Here's your point of contact...!!</p>
        </div>

        <div class="row contact-info">

          <div class="col-md-4">
            <div class="contact-address">
              <i class="ion-ios-location-outline"></i>
              <h3>Address</h3>
              <address>Castle Charis Complex, Kalathipady</address>
              <address>Kottayam, Kerala-686 010, India</address>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-phone">
              <i class="ion-ios-telephone-outline"></i>
              <h3>Phone Number</h3>
              <p><a href="tel:04812571024">0481 257 1024</a></p>
              <p><a href="tel:+919656737009">+91 9656 73 7009</a></p>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-email">
              <i class="ion-ios-email-outline"></i>
              <h3>Email</h3>
              <p><a href="mailto:uniwaretechnologies@gmail.com">uniwaretechnologies@gmail.com</a></p>
              <p><a href="mailto:uniwarehelpline@gmail.com">uniwarehelpline@gmail.com</a></p>
            </div>
          </div>

        </div>

        <div class="form">
          <div id="sendmessage">Your message has been sent. Thank you!</div>
          <div id="errormessage"></div>
          <form action="" method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validation"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validation"></div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div>

      </div>
    </section>

  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Products</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Services</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Store</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="website.aspx">Web Designing</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Partner Program</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Safa Trade Centre<br>
              Railway Station Road<br>
              Kottayam, Kerala - 686 001 <br>
              <strong>Mobile:</strong> +91 9656 73 7009<br>
              <strong>Phone :</strong> 0481 256 1024<br>
              <strong>Email:</strong>uniwaretechnologies@gmail.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-6 col-md-6 footer-newsletter">
            <h4>Reach Us</h4>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3934.0713279352135!2d76.55078331417474!3d9.589120282606197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b062c7ef5a91a2b%3A0xfbe80bcc5a863194!2sUNIWARE+TECHNOLOGIES!5e0!3m2!1sen!2sin!4v1527671196207" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><a href="http://uniwareweb.com">UNIWARE TECHNOLOGIES</a></strong>. All Rights Reserved
      </div>

    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/jquery/jquery-migrate.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/superfish/hoverIntent.js"></script>
  <script src="lib/superfish/superfish.min.js"></script>
  <script src="lib/wow/wow.min.js"></script>
  <script src="lib/waypoints/waypoints.min.js"></script>
  <script src="lib/counterup/counterup.min.js"></script>
  <script src="lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="lib/isotope/isotope.pkgd.min.js"></script>
  <script src="lib/lightbox/js/lightbox.min.js"></script>
  <script src="lib/touchSwipe/jquery.touchSwipe.min.js"></script>

  <script src="contactform/contactform.js"></script>

  <script src="js/main.js"></script>


  
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5e3d2d5a298c395d1ce6afc3/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->




</body>
</html>
