<%@ Page Language="C#" AutoEventWireup="true" CodeFile="website.aspx.cs" Inherits="website" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8">
  <title>Website Development Company In Kerala. Best Business Website With Free SEO. Web Designing At Lowest Cost In Kottayam.</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="Build Stunning And Professional Websites For Your Business. Quality And Search Engine Friendly Web Pages To Increase Volume Of Visitors and Generate More Business"/>
  <meta name="keywords" content="Web Designing In Kottayam, Website Development in Kottayam, Website Development, Web Development, Web Designing, How To Make A Website, Website Development Tools, How Can I Develop A Website, Website Companies Near Me, Web Designer Near Me, Web Designing Company Near Me, Where To Find A Web Designing Company In Kerala, Best Website Development In Kerala, Website At Cheap Rate, Cheap Website Development In Kottayam, Low Cost Website For Business, Personal Website, Website For Events, Portfolio Website, Rate For Website Development, Cost For Website Development, Web Designing Cost In Kerala, Web Designng Company For Educational Institutions, Website Development For Schools, Website For Car Rental Service In Kerala, Website For Tour Company In Kottayam, Website For Hotels And Resorts In Munnar, Website For Homestays In Vagamon, Website Promotion In Kerala, SEO Companies In Kottayam, How To Do SEO, How To Make My Website, How To Get Google Ranking, SEO Tips, SEO Tools, Social Media Marketing, Online Business Promotion, Business Websites, Content Management Website. Search Engine Marketing Company In Kottayam"/>
  <meta name="author" content="Uniware Technologies"/>


  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->


  <script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "Website Development",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue" : "4.6",
    "ratingCount": "32",
    "reviewCount": "18"
  }
}
</script>


<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Uniware Technologies",
  "image" : "http://www.uniwareweb.com/img/logo.png",
  "telephone" : "+91 9656 73 7009",
  "email" : "uniwaretechnologies@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Near Railway Station",
    "addressLocality" : "Kottayam",
    "addressRegion" : "Kerala",
    "addressCountry" : "India",
    "postalCode" : "686 001"
  },
  "url" : "http://www.uniwareweb.com/"
}
</script>

   <link href="img/Icon.ico" rel="icon">
  <link href="img/Icon.ico" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/animate/animate.min.css" rel="stylesheet">
  <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <link href="css/style.css" rel="stylesheet">

</head>

<body>

  <header id="header">
    <div class="container-fluid">
  
      <div id="logo" class="pull-left">
         <a href="#intro"><img src="img/logo.png" alt="UNIWARE TECHNOLOGIES" title="" /></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="home.aspx">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Products</a></li>
          <li><a href="#portfolio">Services</a></li>
          <li class="menu-has-children"><a href="">Store</a>
            <ul>
              <li><a href="#">Barcode Printers</a></li>
              <li><a href="#">Barcode Scanners</a></li>
              <li><a href="#">Barcode Labels</a></li>
              <li><a href="#">Thermal Printer</a></li>
              <li><a href="#">Thermal Paper Rolls</a></li>
              <li><a href="#">Biometric Punching Machine</a></li>
              <li><a href="#">Face Detection Machine</a></li>
              <li><a href="#">Biomatric Access Control</a></li>
              <li><a href="#">RFID Tags & Strips</a></li>
              <li><a href="#">Students & Employees ID</a></li>
              <li><a href="#">Billing Machine</a></li>
              <li><a href="#">Boom Barrier</a></li>
              <li><a href="#">ID Card Printer</a></li>
            </ul>
          </li>
        <li><a href="#team">Career</a></li>
        <li><a href="https://uniwareweb.blogspot.com/" target="_blank">Blog</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <main id="main">

  
  
          

          <div style="position:relative;text-align:center;color:White; width:100%;">

                <img class="img img-fluid" src="img/WebDesigning_Banner.jpg" style="width:100%; margin-top:69px;" alt="Website Development Company In Kottayam" />
                <div style="position:absolute; top:60%; left:15px;  ">
                    <h3 style="color:#d4d1ce; font-weight:500;">Website Development & SEO - KERALA </h3>

               </div>
          </div>

   <section id="contact" class="section-bg wow fadeInUp" style="padding-top:15px; padding-bottom:15px; background-color:rgb(50 186 193);">
      <div class="container">

        <div class="section-header">
          <h3 style="margin-bottom:0px; color:White;">DROP YOUR CONTACT FOR FREE ASSISTANCE</h3>
          <p style="margin-bottom:0px; padding-bottom:12px; color:White;">Just leave your contact here...our expert will contact you very soon..!!</p>
        </div>

        <form id="Form1" runat="server">
        <div class="form">
          <div id="Div2"></div>
          <form action="" method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-5">
                <%--<input type="text" name="name" class="form-control" id="Text1" placeholder="Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />--%>
                <asp:TextBox class="form-control" placeholder="Enter Your Name" ID="TxtName" runat="server"></asp:TextBox>
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-5">
                
                <%--<input type="tel" class="form-control" name="email" id="email1" placeholder="Mobile Number" data-rule="email" data-msg="Please enter a valid email" />--%>
                <asp:TextBox class="form-control" placeholder="Enter Mobile Number" ID="TxtMobile" runat="server"></asp:TextBox>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server"  style="color:Red;" 
                ControlToValidate="TxtMobile" ErrorMessage="Enter a valid mobile number.."  
                ValidationExpression="[0-9]{10}"></asp:RegularExpressionValidator>
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-2">
              <div class="text-center">
                <%--<button type="submit">Submit Enquiry</button>--%>
                
                    <asp:Button ID="CmdSubmit" runat="server" Text="Submit Enquiry" onclick="CmdSubmit_Click"></asp:Button>
               
              </div>
 </form>

              </div>
         </form>
        </div>          
    </section>


    <section id="about" style="padding-top:40px;">
      <div class="container">

      <div class="row">
      <div class="col-sm-1"></div>
       <div class="col-sm-10">
        <header class="section-header">
          <h3>WEB DESIGNING & ONLINE PROMOTION</h3>
          <p style="font-size:15px; text-align:justify; margin-bottom:5px;"> We undertake and develop all type of websites for your personal or business use. We are one of the top web designing companies in Kerala with business relationships and satisfied customers accross the state. We have a dedicated team of developers and designers to fulfill the requirement of our customers with the support of all most modern development environment and platforms. We are designing scalable business or portfoli websites which are responsive in design and compatible for all major devices available now a days, and are friendly for search engine optimisation. </p>
        </header>
        </div> 
        <div class="col-sm-1"></div>
      </div>

      </div>
    </section>



        <section id="about">
      <div class="container">


        <div class="row about-cols" style="margin-bottom:50px;">

          <div class="col-md-3 wow fadeInUp">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/busniess.jpg" alt="Business Website Development" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">BUSINESS WEBSITES </h2>
              <center><p>
                    Attractive and new generation website to promote and increase the volume of your business. Customized and responsive designing.
              </p></center>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/organization.jpg" alt="Website For Organisations" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">WEBSITE FOR ORGANISATIONS</h2>
             <center> <p>
                   Best way to present your organizations functionalities and achievements. We build interactive and stunning website to fulfill your requirements.
              </p></center>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/portfolio.jpg" alt="Portfolio Website Development" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">PORTFOLIO WEBSITES </h2>
              <center><p>
              Design portfolio websites are the prism through which you are constantly evaluated by new clients. Best way to promote yourself in online media.
              </p></center>
            </div>
          </div>

          <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/cms.jpg" alt="Content Management Websites Development" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px;  color:#ff6000;">CMS WEBSITES </h2>
             <center> <p>
                A website which is backed up with a Content Management System software to manage the contents, pages and layouts of your website from anywhere.
              </p></center>
            </div>
          </div>

        </div>

         <div class="row about-cols" style="margin-bottom:50px;">
            
            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/ecommerce.jpg" alt="e Commerce website development in kottayam, kerala" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">e-COMMERCE WEBSITES</h2>
              <center><p>
                Best way to sell your products and services through interractive and customer friendly website. Manage your stock, sale & pricing with admin control panel.
              </p></center>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/seo.jpg" alt="Search Engine Optimisation In Kottayam" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">SEARCH ENGINE OPTIMIZATION</h2>
              <center><p>
                SEO generally means to promote your website in search results to increase the visitors and convert them to your products to acheve your goal.
              </p></center>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/promotion.jpg" alt="Online Advertisement In Google At Kottayam" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">ONLINE BUSINESS PROMOTION</h2>
              <center><p>
                Google Advertisement and keyword optimization to present your website in the top most position of search results, in a Cost Per Click model.
              </p></center>
            </div>
          </div>

            <div class="col-md-3 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col" style="padding-bottom:30px;">
              <div class="img">
                <img src="img/website/domain-registration.jpg" alt="How to register domain or website name" class="img-fluid">
              </div>
              <h2 class="title" style="font-weight:500; font-size:15px; margin-top:15px; color:#ff6000;">DOMAIN REGISTRATION</h2>
              <center><p>
                Register your favourite domain suitable for your websites. Best prices offered with free assistance. Manage all your domains in single platform.
              </p></center>
            </div>
          </div>

         </div>


      </div>
    </section>                      




    <section id="call-to-action" class="wow fadeIn">
      <div class="container text-center">
        <h3>FOR EXPERT ASSISTANCE<br />CALL </h3>
        <h1 style="color:white; font-weight:bolder">+91 9656 73 7009</h1>
        <p> OR Tap the Call Button Below</p>
        <a class="cta-btn" href="tel:+91 9656737009" title="Click To Call Our Expert" data-rel="external">Call</a>
      </div>
    </section>

    <section id="services" style="padding-top:0px;">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3 style="margin-bottom:50px; margin-top:50px;">Key Features</h3>
        </header>

        <div class="row">

          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Modern Designing</a></h4>
            <p class="description">Most modern designing techniques used to make new age websites.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Customized Designing</a></h4>
            <p class="description">Each websites are designed for serving the purpose of the client.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Responsive Structuring</a></h4>
            <p class="description">Websites are developed to make it compatible for modern devices.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Optimized for Page Speed</a></h4>
            <p class="description">Highly optimized Contents, Designs, Matirials etc, are used for page speed</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Geo Tagging</a></h4>
            <p class="description">Integrated map & location tagging included for easy access of your customers.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">SEO Friendly</a></h4>
            <p class="description">Websites are built to provide high results in search engines and other platforms.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Content Management System</a></h4>
            <p class="description">Easy to use and handy content management software to manage the contents from anywhere.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">Interactive Programming</a></h4>
            <p class="description">Interactive and responsive programming adopted to keep communicating with your customers.</p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-star-outline"></i></div>
            <h4 class="title"><a href="">SMS Automation</a></h4>
            <p class="description">Quick and accurate SMS system can be implemented for customer iterractions.</p>
          </div>


        </div>

      </div>
    </section>



    <!--==========================
      Clients Section
    ============================-->
    <section id="clients" class="wow fadeInUp">
      <div class="container">

        <header class="section-header">
          <h3>MAJOR CLIENTS</h3>
        </header>

        <div class="owl-carousel clients-carousel" >
          <img style="margin-right:10px;width:200px;" src="img/clients/Assumption_College.png"  alt="Assumption College Changanacherry"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Alphonsa_college.png" alt="Alphonsa College, Pala"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/BPC_College.png" alt="BPC College, Piravom, Ernakulam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Brilliant.png" alt="Brilliant Studey Centre, Pala"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Baselius_College.png" alt="Baselius College, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/KG_College_Pampady.png" alt="KG College, Pampady, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/MGU_Nursing_College.png" alt="Nursing College, MG University, Manimalakkunnu"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/MGU_DPS.png" alt="Pharmacy College, MG University, Puthuppally, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/SD_College_Kanjirappally.png" alt="SD College, Kanjirappally, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/StMarys_College_Manarcadu.png" alt="St.Marys College, Manarcardu, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/SN_College_Kumarakom.png" alt="SN College, Kumarakom, Kottayam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Sankara_College_Kalady.png" alt="Sree Sankara College, Kalady, Ernakulam"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/VNS_College_Konni.png" alt="VNS College of Arts And Science, Konni, Pathanamthitta"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Bhavapriya.jpg" alt="BavaPriya School of Music and Dance"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/Kochintaxi.png" alt="Cochin taxi Rental"/>
          <img style="margin-right:10px;width:200px;" src="img/clients/LaggageToLagoon.png" alt="Laggae To Lagoon"/>
           <img style="margin-right:10px;width:200px;" src="img/clients/Muncipality.png" alt="Kottayam-Muncipality"/>

        </div>

      </div>
    </section><!-- #clients  

    <!--==========================
      Clients Section
    ============================-->



<%--    <section id="portfolio"  class="section-bg" >
      <div class="container">

        <div class="row portfolio-container">

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emark.jpg" class="img-fluid" alt="e-Mark Classic Sales And Billing Software">
                <a href="img/portfolio/emark.jpg" data-lightbox="portfolio" data-title="App 1" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark Classic</a></h4>
                <h6>GST Enabled Billing & Accounting Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/escholar.jpg" class="img-fluid" alt="e-Scholar College Automation Software Package In Kerala">
                <a href="img/portfolio/escholar.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Scholar WEB</a></h4>
                <h6>A Complete College Automation Software Package</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcare.jpg" class="img-fluid" alt="SmartCARE HMS Hospital Management Software In Kerala">
                <a href="img/portfolio/smartcare.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">SmartCARE HMS</a></h4>
                <h6>Fully Featured Hospital Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/emarkweb.jpg" class="img-fluid" alt="e-Mark Online Software For Billing & Accounting With GST">
                <a href="img/portfolio/emarkweb.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">e-Mark WEB</a></h4>
                <h6>GST Ready Online Billing & Accounting Software including mobile app</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcrm.jpg" class="img-fluid" alt="Customer Relationship Management Software">
                <a href="img/portfolio/smartcrm.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CRM</a></h4>
                <h6>Well Organized Customer Relationship Management Software</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/whitestore.jpg" class="img-fluid" alt="e-Commerce Shopping Cart">
                <a href="img/portfolio/whitestore.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">White Store</a></h4>
                <h6>Complete e-Commerce Shopping Cart and Online Store Management System</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/timestamp.jpg" class="img-fluid" alt="Biometric Attendance System using Finger Print, Palm And Face Reader">
                <a href="img/portfolio/timestamp.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">TimeStamp Pro</a></h4>
                <h6>Biometric Punching system for Time & Attendance Management</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/gdesk.jpg" class="img-fluid" alt="g-Desk Gymnesium Software For Membership Management, Progress Analysis And Fee Collection">
                <a href="img/portfolio/gdesk.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">G-Desk</a></h4>
                <h6>Customizable Gymnesium & Health club management system</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/smartcms.jpg" class="img-fluid" alt="Content Management System For Dynamic Website">
                <a href="img/portfolio/smartcms.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Smart CMS</a></h4>
                <h6>Free To Use Content Management System for business websites</h6>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>--%>


  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Products</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Services</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Store</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Referral Program</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Partner Program</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Safa Trade Centre<br>
              Railway Station Road<br>
              Kottayam, Kerala - 686 001 <br>
              <strong>Mobile:</strong> +91 9656 73 7009<br>
              <strong>Phone :</strong> 0481 256 1024<br>
              <strong>Email:</strong>uniwaretechnologies@gmail.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-6 col-md-6 footer-newsletter">
            <h4>Reach Us</h4>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3934.0713279352135!2d76.55078331417474!3d9.589120282606197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b062c7ef5a91a2b%3A0xfbe80bcc5a863194!2sUNIWARE+TECHNOLOGIES!5e0!3m2!1sen!2sin!4v1527671196207" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><a href="http://uniwareweb.com">UNIWARE TECHNOLOGIES</a></strong>. All Rights Reserved
      </div>

    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/jquery/jquery-migrate.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/superfish/hoverIntent.js"></script>
  <script src="lib/superfish/superfish.min.js"></script>
  <script src="lib/wow/wow.min.js"></script>
  <script src="lib/waypoints/waypoints.min.js"></script>
  <script src="lib/counterup/counterup.min.js"></script>
  <script src="lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="lib/isotope/isotope.pkgd.min.js"></script>
  <script src="lib/lightbox/js/lightbox.min.js"></script>
  <script src="lib/touchSwipe/jquery.touchSwipe.min.js"></script>

  <script src="contactform/contactform.js"></script>

  <script src="js/main.js"></script>


  
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5e3d2d5a298c395d1ce6afc3/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->


</body>

</html>
